services:
    rag-elasticsearch:
        image: elasticsearch:8.12.2
        container_name: rag-elasticsearch
        ports:
            - "9200:9200"
        environment: ['CLI_JAVA_OPTS=-Xms512m -Xmx512m','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false', 'http.cors.allow-origin=http://localhost:8180', 'http.cors.enabled=true']
        volumes:
            -   ./elasticsearch/synonyms:/usr/share/elasticsearch/config/synonyms
        networks:
            - local
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: 2048M
                reservations:
                    cpus: '0.50'
                    memory: 1024M
    rag-elasticvue:
        image: cars10/elasticvue
        container_name: rag-elasticvue
        ports:
            - "8180:8080"
        networks:
            - local
    rag-langchain:
        build: langchain/docker
        container_name: rag-langchain
        volumes:
          - ./langchain/app:/var/www/app
        networks:
          - local
    rag-ollama:
        image: ollama/ollama:latest
        container_name: rag-ollama
        ports:
          - 11434:11434
        networks:
          - local
networks:
    local:
